[package]
name = "storm"
version = "0.0.2"
authors = ["Joe Cumbo <mooman219@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.12"
beryllium = '*'
cgmath = "0.17"
log = "0.4"
simple_logger = "1.3.0"
image = "0.19"
parking_lot = "0.7"
hashbrown = "0.2"
rusttype = "0.7"
unicode-normalization = "0.1.8"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3