[package]
name = "storm"
version = "0.0.1"
authors = ["Joe Cumbo <mooman219@gmail.com>"]

[dependencies]
gl = "0.10"
glutin = "0.16"
cgmath = "0.15"
bounded-spsc-queue = "0.3"
log = "0.4"
image = "0.16"