[package]
name = "storm"
version = "0.5.0"
authors = ["Joe Cumbo <mooman219@gmail.com>"]
description = "2D game engine designed for performance"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mooman219/storm"
keywords = ["game", "engine", "2D", "graphics"]
categories = ["game-engines"]
edition = "2018"
exclude = [
    "examples_old/*",
]

[badges]
maintenance = { status = "experimental" }

[dependencies]
gl = "0.13.0"
beryllium = "0.0.17"
cgmath = "0.17.0"
log = "0.4.7"
simple_logger = "1.3.0"
png = "0.14"
hashbrown = "0.5.0"
rusttype = "0.7.7"
unicode-normalization = "0.1.8"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3
