[package]
name = "storm"
version = "0.5.0"
authors = ["Joe Cumbo <mooman219@gmail.com>"]
description = "A personal 2D game engine designed for performance"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/storm"
homepage = "https://github.com/mooman219/storm"
repository = "https://github.com/mooman219/storm"
keywords = ["game", "engine", "2D", "graphics"]
categories = ["game-engines"]
edition = "2018"
exclude = ["examples_older/**", "examples_old/**", "examples/**"]

[badges]
maintenance = { status = "experimental" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = { version = "0.2", features = ["color"] }
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "Window",
]}
wasm-bindgen = { version = "0.2" } 
winit = { version = "0.24", features = [
    "web-sys"
]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.26"
winit = "0.24" 

[dependencies]
simple_logger = "1.13"
instant = "0.1.9"
glow = "0.9"
cgmath = "0.18"
log = "0.4"
png = "0.14"
hashbrown = "0.11"
fontdue = "0.6"
unicode-normalization = "0.1"

[profile.release]
lto = "thin"
