# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#match_block_trailing_comma
match_block_trailing_comma = true

# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#max_width
max_width = 120

# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#reorder_imports
reorder_imports = true
